### ISSUE TITLE
Update README.md with basic information

### ISSUE THREAD

**Issue by joncison** [edamontology/pubfetcher#1]
What this tool is for, a little bit of background information (bio.tools, PubMed etc).  Just a few lines would do.

**Comment by joncison** [comment]
@Ahto123 or @jaanisoe can you please take care of this?

**Comment by jaanisoe** [comment]
Comprehensive documentation is now available at: https://github.com/edamontology/pubfetcher/wiki (I maybe overdid it).

As a side note, PubFetcher is for fetching publications (and web pages). It is used both by [EDAMmap](https://github.com/edamontology/edammap) and [PubMedApps](https://github.com/edamontology/edammap/tree/master/pubmedapps). PubMedApps (preliminary name, I guess) is the application for finding potential tools from the literature. It currently lives in the EDAMmap repository and uses the PubFetcher library to download all required data. The core of PubMedApps is more or less done, it requires work on selecting publication IDs to search tools from and work on outputting results in a format importable to bio.tools. I'll try to finish PubMedApps in the coming weeks (along with a README).

Some links between pages of PubFetcher documentation are not working correctly currently, when that's fixed I'll close the issue.

**Comment by joncison** [comment]
Really nice, much appreciated @jaanisoe.  Let's take a call in Oct or Nov with @hansioan so we can roadtest PubMedApps, and see how we can put it into a curation/production environment.

**Comment by jaanisoe** [comment]
The [README.md](https://github.com/edamontology/pubfetcher/blob/develop/README.md) has now basic info, more thorough documentation is at https://pubfetcher.readthedocs.io/.
